---
- name: Check if user exists
  ansible.builtin.command:
    id {{ user.name }}
  become: true
  ignore_errors: true
  register: user_exists_cmd

- name: Create/update group
  ansible.builtin.group:
    name: "{{ user.name }}"
    gid_min: 1000
    state: "{{ user.state | default('present') }}"

- name: Create/update user
  ansible.builtin.user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ ['adm', 'sudo'] if user.is_superuser else '' }}"
    state: "{{ user.state  | default('present') }}"
    shell: "{{ '/usr/bin/false' if not user_has_password else '/bin/bash' }}"
    # We use a '*' password and handle users with password later
    password: '*'
    update_password: "on_create"

- name: Force user to set password on first login
  when: user_has_password and user_exists_cmd.rc != 0
  ansible.builtin.command: "passwd -e -d {{ user.name }}"
