---
# Official docs for proxmox node install
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster

# network config for proxmox hosts


- name: run proxmox node install
  ansible.builtin.include_role:
    name: lae.proxmox
    tags: proxmox