---
# Official docs for proxmox node install
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster


- name: prepare partitions
  ansible.builtin.import_tasks: parted.yml

- name: prepare zpool and datasets
  ansible.builtin.include_role:
    name: aisbergg.zfs
  vars:
    zfs_manage_repository: true
    zfs_service_zed_enabled: true
    zfs_scrub_schedule: monthly
    zfs_trim_schedule: weekly
    zfs_pools: "{{ proxmox_node_zfs_pools }}"
    zfs_filesystems: "{{ proxmox_node_zfs_filesystems }}"
    zfs_volumes: "{{ proxmox_node_zfs_volumes }}"
    # we prefer to use inheritance as much as possible as defaults
    zfs_filesystems_properties_defaults: {}
    zfs_zrepl_enabled: false  # we use sanoid / syncoid instead
  tags: zfs

- name: run proxmox node install
  ansible.builtin.include_role:
    name: lae.proxmox
  vars:
    # we are handling zfs stuff with aisbergg.zfs, above
    # but if we don't put this, the role will disable zfs loading !
    pve_zfs_enabled: true
    pve_zfs_zed_email: "{{ proxmox_node_alerts_email }}"

  tags: proxmox

# TODO: configure network