# Check and eventually create partitions
---

- name: Install parted
  ansible.builtin.package:
    name: parted
    state: present

- name: "Check or create partitions"
  community.general.parted:
    device: "{{ item.device }}"
    state: "{{ item.state | default('present') }}"
    fs_type: "{{ item.fs_type }}"
    flags: "{{ item.flags | default([]) }}"
    label: "{{ item.label | default('gpt') }}"
    number: "{{ item.number }}"
    part_start: "{{ item.part_start | default('1') }}"
    part_end: "{{ item.part_end | default('100%')}}"
    part_type: "{{ item.part_type | default('primary') }}"
    resize: "{{ item.resize | default('false') }}"
  check_mode: "{{ not proxomox_node_mkparts }}"
  loop: "{{ proxmox_node_partitions }}"
  when: proxmox_node_partitions is defined
  register: proxmox_node_parted_result
  loop_control:
    label: "{{ item.device }} - {{ item.number }} - {{ item.state }}"

- name: "Check if partitions are expected ones"
  # if proxmox_node_mkparts is false, and changes would have occurred
  # it means partitions are not as expected
  ansible.builtin.assert:
    that:
    - proxmox_node_parted_result.results | selectattr('changed', 'equalto', true) | list | length == 0
    fail_msg: |
      Partitions are not as expected, if you want to create them,
      use -e 'proxomox_node_mkparts=true' on your command line
    success_msg: "Partitions are as expected"
  when: "( proxmox_node_partitions is defined ) and ( not proxomox_node_mkparts )"