
proxmox_node_zfs_pools:
  - name: hdd-zfs
    vdev: raidz1 sda5 sdb5 sdc5 sdd5 cache nvme0n1 nvme1n1
    properties:
      ashift: "12"
    filesystem_properties: "{{ proxmox_node_zfs_pools_filesystem_properties_defaults }}"