# Install and manage iptables
---
- name: Install iptables and netfilter-persistent
  ansible.builtin.apt:
    pkg:
      - ipset
      - iptables
      - netfilter-persistent
      - iptables-persistent
      - ipset-persistent
    state: present
    update_cache: true

- name: Setup the rules for iptables v4
  ansible.builtin.template:
    src: iptables_rules.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0600'
  vars:
    iptables_rules_version: v4

- name: Setup the rules for iptables v6
  ansible.builtin.template:
    src: iptables_rules.j2
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: '0600'
  vars:
    iptables_rules_version: v6

- name: Setup the rules for ipset
  ansible.builtin.template:
    src: ipsets.j2
    dest: /etc/iptables/ipsets
    owner: root
    group: root
    mode: '0600'

- name: Reload ipset rules
  ansible.builtin.shell: >-
    ipset restore -exist < /etc/iptables/ipsets

- name: Reload iptables rules
  community.general.iptables_state:
    ip_version: "ip{{ item }}"
    path: /etc/iptables/rules.{{ item }}
    state: restored
    wait: 6
  loop: ['v4', 'v6']