---
base_timezone: Europe/Paris

base_unattended_mail: "{{ secrets_infra_email }}"

base_unattended_mail_only_on_error: true

base_unattended_remove_unused_dependencies: true

base_unattended_update_package_list: 1

base_unattended_download_upgradeable: 1

base_unattended_autoclean_interval: 1

base_unattended_clean_interval: 1

base_unattended_verbose: 1
