---
- name: Common configuration
  # limit to host that were configured using this role
  hosts:
  - ops_installed
  gather_facts: true
  become: true
  roles:
    - role: base
      tags: base
    - role: sshd
      tags: ssh
    - role: oefenweb.fail2ban
      tags: fail2ban
# TODO
#    - role: nullmailer
#      tags: mail
#    - role: munin-node
#      tags: [munin, munin-node]
#    - firewall DENY input + verify ssh rule
#    - set locale en_US + fr_FR
