---
- name: Common configuration
  hosts: all:!non_ansible_hosts
  gather_facts: true
  become: true
  roles:
    - role: base
      tags: base
    - role: sshd
      tags: ssh
    - role: nullmailer
      tags: mail
    - role: iptables
      tags: firewall
    - role: fail2ban-nftables
      tags: fail2ban
# TODO
#    - role: munin-node
#      tags: [munin, munin-node]
#    - firewall DENY input + verify ssh rule
#    - set locale en_US + fr_FR
