---

- name: run base fail2ban role
  ansible.builtin.include_role:
    name: oefenweb.fail2ban
  vars:
    fail2ban_banaction: "nftables[type=multiport]"
    fail2ban_banaction_allports: "nftables[type=multiport]"
    fail2ban_chain: fail2ban
    fail2ban_loglevel: "{{ fail2ban_nftables_loglevel }}"
    fail2ban_ignoreips: "{{ fail2ban_nftables_ignoreips }}"


- name: "copy fail2ban needed config files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/{{ item | replace('--', '/') }}"
  notify: restart fail2ban
  loop:
    # fix nftables action
    - action.d--nftables.local