---

- name: "Ensure no over-hardening prevent systemd-hostnamed.service to start (on Deb 11, full is OK, strict is KO)"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-hostnamed.service
    regexp: '^ProtectSystem='
    line: ProtectSystem=full
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11'
  notify:
    - "Reload systemd"
    - "Restart systemd-hostnamed"
  tags:
    - host
    - system

- name: "Set server hostname"
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  ignore_errors: true
  register: hostname_result
  failed_when: >
    hostname_result.failed and
    'read-only filesystem' not in hostname_result.msg and
    'Could not set pretty hostname' not in hostname_result.msg
  tags:
    - host

- name: "Proper /etc/hosts reference to localhost"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[\s\t]+'
    line: '127.0.0.1 {{ inventory_hostname }}.localhost localhost'
    state: present
  tags:
    - host

- name: "Proper /etc/hosts reference to FQDN"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address | regex_escape() }}[\s\t]+'
    line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }}.{{ host_domain }} {{ inventory_hostname }}'
    insertafter: '^127\.0\.0\.1[\s\t]+'
    state: present
  tags:
    - host

- name: "Proper /etc/hosts ipv6 reference to FQDN"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv6.address | regex_escape() }}[\s\t]+'
    line: '{{ ansible_default_ipv6.address }} {{ inventory_hostname }}.{{ host_domain }} {{ inventory_hostname }}'
    insertafter: '^127\.0\.0\.1[\s\t]+'
    state: present
  when: "ansible_default_ipv6.address is defined"
  tags:
    - host

- name: "No /etc/hosts reference to 127.0.1.1"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1[\s\t]+'
    state: absent
  tags:
    - host

- name: "Set ansible_fqdn fact"
  ansible.builtin.set_fact:
    ansible_fqdn: "{{ inventory_hostname }}.{{ host_domain }}"
