---
- name: "Set timezone"
  community.general.timezone:
    name: "{{ base_timezone }}"
  notify:
    - "Reload systemd"
    - "Restart systemd-timesyncd"
  tags:
    - system

- name: "Ensure legacy ntp daemons are not installed"
  ansible.builtin.apt:
    pkg: ntp
    state: absent
  tags:
    - system

- name: "Ensure systemd-timesyncd is installed"
  ansible.builtin.apt:
    pkg: systemd-timesyncd
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11'
  tags:
    - system

- name: "Ensure no over-hardening prevent systemd-timedated to start (on Deb 11, full is OK, strict is KO)"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-timedated.service
    regexp: '^ProtectSystem='
    line: ProtectSystem=full
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11'
  notify:
    - "Reload systemd"
  tags:
    - system

- name: "Ensure no over-hardening prevent systemd-timesyncd to start (on Deb 11, full is OK, strict is KO)"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-timesyncd.service
    regexp: '^ProtectSystem='
    line: ProtectSystem=full
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11'
  notify:
    - "Reload systemd"
  tags:
    - system

- name: "Set systemd-timesyncd daemon configuration"
  ansible.builtin.template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: '0644'
  notify:
    - "Reload systemd"
    - "Restart systemd-timesyncd"
  tags:
    - system

- name: "Ensure systemd-timesyncd daemon autostart"
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true
    state: started
  tags:
    - system
