---

- name: run base fail2ban role
  ansible.builtin.include_role:
    name: oefenweb.fail2ban
  vars:
    fail2ban_services: "{{ fail2ban_iptables_services }}"
    fail2ban_backend: "{{ fail2ban_iptables_backend }}"
    fail2ban_loglevel: "{{ fail2ban_iptables_loglevel }}"
    fail2ban_ignoreips: "{{ fail2ban_iptables_ignoreips }}"

- name: "copy fail2ban needed config filters or other files"
  ansible.builtin.include_tasks: copy_jail_files.yml
  vars:
    jail: "{{ item.name }}"
  loop: "{{ fail2ban_iptables_services }}"
