---
- name: Execute upstream sshd role
  ansible.builtin.import_role:
    name: willshersystems.sshd

# TODO: remove from here
- name: Install mosh
  ansible.builtin.apt:
    pkg: mosh
    state: present
  tags:
    - system
    - mosh

- name: Authorize ssh public keys from github for ansible operator
  ansible.posix.authorized_key:
    user: '{{ ansible_ssh_user }}'
    key: '{{ sshd_github_url }}/{{ item.github_name | default(item.name) }}.keys'
  loop: '{{ sshd_github_authorized_users }}'

- name: Revoke ssh public keys from github for ansible operator
  ansible.posix.authorized_key:
    user: '{{ ansible_ssh_user }}'
    key: '{{ sshd_github_url }}/{{ item.github_name | default(item.name) }}.keys'
    state: absent
  loop: '{{ sshd_github_revoked_users }}'
